server:
  port: 8888
  servlet:
    session:
      tracking-modes:
      - cookie

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver

  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        500MB

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:mapper/**/*.xml